import { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    id: 'project-udsm-network-security',
    title: 'University of Dar es Salaam Network Security Analysis and Penetration Test',
    summary: 'Final Year Project at University of Dar es Salaam, 2009. Conducted security analysis and penetration testing on the University of Dar es Salaam Network.',
    startDate: '2009',
    endDate: '2009',
    technologies: ['Network Security', 'Penetration Testing'],
  },
  {
    id: 'project-scrum-team-management',
    title: 'Scrum Team Management System',
    summary: 'Honours Project at University of Cape Town, 2010. Developed a window-based application for managing Scrum teams at Korbitec Company.',
    startDate: '2010',
    endDate: '2010',
    technologies: ['WPF', 'C#'],
  },
  {
    id: 'project-visually-impaired-app',
    title: 'Enabling Visually Impaired People to Use Touch Screen Phones',
    summary: 'Masters Project at University of Cape Town, 2015. Created an Android-based application to assist visually impaired individuals with touchscreen phones.',
    startDate: '2015',
    endDate: '2015',
    technologies: ['Android', 'Java'],
    featured: true,
  },
  {
    id: 'project-budget-entertainment',
    title: 'Budget Entertainment Resort Limited',
    summary: 'Personal IT Project, 2009. Developed a web-based application for resort management.',
    startDate: '2009',
    endDate: '2009',
    technologies: ['PHP', 'MySQL', 'jQuery'],
  },
  {
    id: 'project-bahari-lodge',
    title: 'Bahari Lodge: Bed and Breakfast',
    summary: 'Personal IT Project, 2009. Built a web-based application for bed and breakfast management.',
    startDate: '2009',
    endDate: '2009',
    technologies: ['PHP', 'MySQL', 'jQuery'],
  },
  {
    id: 'project-juiceparlour',
    title: 'Ordering Management System (JuiceParlour)',
    summary: 'Personal IT Project, 2011. Created a window-based application for managing orders in a juice parlor.',
    startDate: '2011',
    endDate: '2011',
    technologies: ['WPF', 'C#', 'SQL Server 2008'],
  },
  {
    id: 'project-stock-management',
    title: 'Stock Management System',
    summary: 'Personal IT Project, 2012. Developed a window-based application for stock management.',
    startDate: '2012',
    endDate: '2012',
    technologies: ['WPF', 'C#', 'SQL Server 2008'],
  },
  {
    id: 'project-nikumbushe',
    title: 'Nikumbushe (Proximity Reminder)',
    summary: 'Personal IT Project, 2013. Built an Android mobile application for proximity reminders.',
    startDate: '2013',
    endDate: '2013',
    technologies: ['Android'],
  },
];

